// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCADUJpwE8KfRczvc8i34B1z8cMfxzF9hA',
    appId: '1:270436013421:android:be6cf11fda9dc5c155b664',
    messagingSenderId: '270436013421',
    projectId: 'voyage-16bd4',
    databaseURL: 'https://voyage-16bd4-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-16bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtoSaqA5rQTTX3oeFHyiENTC77c6rMqMI',
    appId: '1:270436013421:ios:8cb5dd998c50ba6055b664',
    messagingSenderId: '270436013421',
    projectId: 'voyage-16bd4',
    databaseURL: 'https://voyage-16bd4-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-16bd4.appspot.com',
    iosClientId: '270436013421-75bogoag9jpaish6hip9qvd7rdrddiuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );
}
